#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

getScriptPath() {
	echo ${0%/*}/
}

interpDirPath=$(getScriptPath)../322-interps
testDirPath=$(getScriptPath)/2-test

for L1TestFile in $( find $testDirPath -name '*L1' )
do

# Remove file extension
testName=$(echo "$L1TestFile" | sed 's,.*/\([^/]*\)\..*,\1,g')
testPath="$testDirPath/$testName"

# interpret
"./$interpDirPath/L1" "$testPath.L1" > "$testPath.L1out"
"./$interpDirPath/L2" "$testPath.L2" > "$testPath.L2out"


# Compare
if cmp -s "$testPath.L1out" "$testPath.L2out"; then
  : # files are the same
  printf "%20s: SUCCESS\n" $testName
else
  : # files are different
  printf "%20s: FAILED\n" $testName
  diff "$testPath.L1out" "$testPath.L2out"
fi

# Cleanup
rm "$testPath.L1out" "$testPath.L2out"

done

IFS=$SAVEIFS
