#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo "\n\b")

for spillPath in $( find "../spill-test" -name '*L2f' )
do

# Remove file extension
echo $spillPath
testName=$(echo "$spillPath" | sed 's,.*/\([^/]*\)\..*,\1,g')
echo $testName
outFile="../spill-test/$testName"

# Spill

./spill "$spillPath" > "$outFile.txt"

# Compare
cat "$outFile.sres" | tr '\n' ' ' > "$outFile.nice"       
if diff -wB --strip-trailing-cr "$outFile.txt" "$outFile.nice" > /dev/null
then
  : # files are the same
  printf "\n%20s: SUCCESS\n" $testName
else
  : # files are different
  printf "\n%20s: FAILED\n" $testName
  diff -wBy -W 90 --strip-trailing-cr --suppress-common-lines "$outFile.txt" "$outFile.nice"
fi

# Cleanup
rm "$outFile.txt" "$outFile.nice"

done

IFS=$SAVEIFS
