#!/bin/sh

getScriptPath() {
	echo ${0%/*}
}

scriptPath=$(getScriptPath)
libPath=$scriptPath/lib

# Compile
"$scriptPath/L3c-bin" "$1" > "$scriptPath/$$.L2"

# Remove trailing parenthesis
L2Code=`cat "$scriptPath/$$.L2"`
echo ${L2Code%?} > "$scriptPath/$$.L2"

# Add L2 Libraries
for L2Lib in $( find "$libPath" -name '*l2f' )
do
cat "$L2Lib" >> "$scriptPath/$$.L2"
done

# Add trailing parenthesis
echo ")" >> "$scriptPath/$$.L2"

# Print the L2 program to stdout
cat "$scriptPath/$$.L2"

# Cleanup
rm "$scriptPath/$$.L2"
