#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

# Compile
./L3c-bin "$1" > "$$".L2

# Remove trailing parenthesis
L2Code=$(<"$$".L2)
set -- $L2Code
echo ${L2Code%?} > "$$".L2

# Add L2 Libraries
for L2Lib in $( find ./lib -name '*L2f' )
do
cat $L2Lib >> "$$".L2
done

# Add trailing parenthesis
echo ")" >> "$$".L2

# Print the L2 program to stdout
cat "$$".L2

# Cleanup
rm "$$".L2

IFS=$SAVEIFS
