#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

getScriptPath() {
	echo ${0%/*}/
}

# Compile

cat $(getScriptPath)/header.s > "$$".s
$(getScriptPath)/L1c-bin "$1" >> "$$".s
cat $(getScriptPath)/footer.s >> "$$".s

# Assemble
as -32 -o "$$".o "$$".s

# Link
gcc -m32 -o a.out "$$".o $(getScriptPath)/runtime/runtime.o

# Cleanup
rm "$$".s "$$".o

IFS=$SAVEIFS
