#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

getScriptPath() {
	echo ${0%/*}/
}

#preprocess 
./L1c-preprocessor "$1" > "$$".L1

# Compile

cat header.s > "$$".s
$(getScriptPath)/L1c-bin "$1" >> "$$".s
cat footer.s >> "$$".s

# Assemble
as -32 -o "$$".o "$$".s

# Link
gcc -m32 -o a.out "$$".o runtime/runtime.o

# Cleanup
rm "$$".s "$$".o "$$".L1

IFS=$SAVEIFS
