#!/bin/sh

getScriptPath() {
	echo ${0%/*}/
}

# Compile
cat header.s > prog.s
$(getScriptPath)/L1c-bin $1 >> prog.s
cat footer.s >> prog.s

# Assemble
as -32 -o prog.o prog.s

# Link
gcc -m32 -o a.out prog.o runtime/runtime.o

# Cleanup
rm prog.s prog.o
