#!/bin/sh

# Play nice with spaces in filenames
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

getScriptPath() {
	echo ${0%/*}/
}

testDirPath=$(getScriptPath)../1-test

for L1Path in $( find $testDirPath -name '*L1' )
do

# Remove file extension
testName=$(echo "$L1Path" | sed 's,.*/\([^/]*\)\..*,\1,g')
outFile="$testDirPath/$testName"

#compile
./L1c "$L1Path"

# Run
./a.out > "$outFile.txt"

# Compare
if cmp -s $outFile.txt $outFile.res; then
  : # files are the same
  printf "%20s: SUCCESS\n" $testName
else
  : # files are different
  printf "%20s: FAILED\n" $testName
  diff "$outFile.txt" "$outFile.res"
fi

# Cleanup
rm a.out "$outFile.txt"

done

IFS=$SAVEIFS